
---
title: "Canonical Correlation Analysis"
author: "S18827"
date: "2024-05-06"
output: html_document
---
```{r}
library(tidyverse)
library(corrplot)
```

```{r}
data3 <- read_csv("../Data/crop_price_prediction.csv")
m <- cor(data3[3:9])
corrplot(m, method = 'circle')
```



```{r}
data <- read_csv("../Data/scrap price.csv")
numeric_cols <- sapply(data, is.numeric)
numeric_no_missing <- colSums(is.na(data[numeric_cols])) == 0
data <- data[numeric_cols] [numeric_no_missing]
m <- cor(data)
corrplot(m, method = 'circle')
```
```{r}
data <- read_csv("../Data/StressLevelDataset.csv")
numeric_cols <- sapply(data, is.numeric)
numeric_no_missing <- colSums(is.na(data[numeric_cols])) == 0
data <- data[numeric_cols] [numeric_no_missing]
data <- scale(data)
m <- cor(data)
corrplot(m, method = 'circle')
colnames(data)

```



```{r}
data <- read_csv("../Data/avgIQpercountry.csv")
numeric_cols <- sapply(data, is.numeric)

data <- data[numeric_cols] %>% na.omit(data)
m <- cor(data)
corrplot(m, method = 'circle')
```

```{r}
data <- read_csv("../Data/led.csv")
numeric_cols <- sapply(data, is.numeric)
data <- data[numeric_cols] %>% na.omit()
m <- cor(data)
corrplot(m, method = 'circle')

colnames(data)
```

```{r}
data <- read_csv("../Data/cancer patient data sets.csv")
numeric_cols <- sapply(data, is.numeric)
data <- data[numeric_cols] %>% na.omit()
m <- cor(data)
corrplot(m, method = 'circle')

colnames(data)
```



```{r}
data <- read_csv("../Data/Economy vs Rice production in Sri Lanka.csv")
numeric_cols <- sapply(data, is.numeric)
data <- data[numeric_cols] %>% na.omit() 
data <- scale(data)
m <- cor(data)
m
corrplot(m, method = 'circle')
```




```{r}
data <- read_csv("../Data/scrap price.csv")
numeric_cols <- sapply(data, is.numeric)
data <- data[numeric_cols] %>% na.omit() 
data <- scale(data)
m <- cor(data)
m
corrplot(m, method = 'circle')
```

```{r}
data <- read_csv("../Data/MLR2.csv")
numeric_cols <- sapply(data, is.numeric)
data <- data[numeric_cols] %>% na.omit() 
data <- scale(data)
m <- cor(data)
m
corrplot(m, method = 'circle')
colnames(data)
```


```{r}
data <- read_csv("../Data/rentcrime.csv")
numeric_cols <- sapply(data, is.numeric)
data <- data[numeric_cols] %>% na.omit() 
data <- scale(data)
m <- cor(data)
m
corrplot(m, method = 'circle')
colnames(data)

```

```{r}

numeric_cols <- sapply(data, is.numeric)
data <- data[numeric_cols] %>% na.omit() 
data <- scale(data)
m <- cor(data)
m
corrplot(m, method = 'circle')
colnames(data)
```
